### ISSUE TITLE
Inefficient code in discard?

### ISSUE THREAD

**Issue by Smattr** [LuminosoInsight/ordered-set#19]
I think perhaps I'm missing something, but it seems to me the following replaces an O(n) operation with an O(1) operation, leaving functionality identical.

```
diff --git a/ordered_set.py b/ordered_set.py
index bf88cd8..118672e 100644
--- a/ordered_set.py
+++ b/ordered_set.py
@@ -160,7 +160,7 @@ class OrderedSet(collections.MutableSet):
         *does* raise an error when asked to remove a non-existent item.
         """
         if key in self:
-            i = self.items.index(key)
+            i = self.map[key]
             del self.items[i]
             del self.map[key]
             for k, v in self.map.items():
```

I initially thought perhaps the index was looked up via the list because the indices in the map weren't necessarily up to date, but the trailing loop updates them when deleting an element. Is there some other reason the list needs to be used for the lookup here? Thanks for your time.

**Comment by rspeer** [comment]
Hi, I missed this until now. Thanks for the bug report. Indeed that would be a better operation; I merged the PR that introduced `discard` without noticing that it was running `.index()` on a list.

**Comment by rspeer** [comment]
My co-worker points out that there's still an unavoidable `O(n)` operation involved here, which is `del self.items[i]`, so this is only faster by a constant factor.
