### ISSUE TITLE
Add support for typing annotations

### ISSUE THREAD

**Issue by nicoulaj** [LuminosoInsight/ordered-set#26]
It would be nice if OrderedSet supported PEP 484 typing module, so that we can do in Python 3:
```
my_set: OrderedSet[Context] = OrderedSet()
```

Right now pycharm/pylint flag it as a typing error:
```
Class 'type' does not define '__getitem__', so the '[]' operator cannot be used on its instances
```
Related: PyCQA/pylint#1657

**Comment by rspeer** [comment]
That sounds helpful, but I have no experience creating new parameterized types in Python. Could you make a pull request?
