### ISSUE TITLE
"native" implementation on python 3.7? 

### ISSUE THREAD

**Issue by burnpanck** [LuminosoInsight/ordered-set#32]
Since in python 3.7 the insertion-order preservation nature of dict objects [has been declared](https://mail.python.org/pipermail/python-dev/2017-December/151283.html) to be an official part of the Python language spec (see [What’s New In Python 3.7](https://docs.python.org/3.7/whatsnew/3.7.html)), `dict` is already almost an ordered-set, except for that it doesn't have the interface of a set. Likely, wrapping `dict` such that it's keys are exposed with the interface of `ordered-set` would be more efficient than the python implementation.

**Comment by rspeer** [comment]
A simple implementation of this would strike me as similar to #24, which didn't work out. This OrderedSet acquired different use cases than plain ordered dicts, and I believe that any straightforward wrapping of `dict` would perform badly in those use cases.

In particular, you can look up an item in an OrderedSet efficiently by its ordered index, as in "what's the 20th item in this set?", and I don't think the API of `dict` provides for this.

However, a complex implementation might do the job. I can imagine a C extension might be able to do efficient indexed lookups if it punches through the `dict` API into its internal representation.

**Comment by burnpanck** [comment]
Ah I see. Was just a thought anyway.
