### ISSUE TITLE
Wanting to do range queries with OrderedSet

### ISSUE THREAD

**Issue by winash12** [LuminosoInsight/ordered-set#34]
I have a set of data values that are sorted on which I want to do range queries such as the ones here - [https://stackoverflow.com/questions/1314650/using-java-map-for-range-searches](url)

Is that possible with OrderedSet ? Something like the OrderedSet in Redis - [https://redis.io/commands/zrange](url)

**Comment by rspeer** [comment]
OrderedSet isn't about sorted keys. I'm sure you can accomplish what you want to with Python but it doesn't have anything to do with this library.
