### ISSUE TITLE
Efficiency of difference_update is much worse than set

### ISSUE THREAD

**Issue by Erotemic** [LuminosoInsight/ordered-set#45]
I use ordered-set quite a bit, and I noticed the difference_update op was taking an extremely long time. 

After looking into it I found that the current implementation of difference_update makes M calls to discard where M is the number of items to remove. 

```python
        for item in it.chain.from_iterable(sets):
            self.discard(item)
```

Then I took a look at the discard logic and it actually needs to make an O(N) loop to update indices after each discard.

I wrote a benchmark script to investigate how much of a problem this causes: 

```python

"""
Requirements:
    pip install timerit
"""
import timerit
import copy
import ordered_set


def benchmark_difference_update():
    N = 1000
    items = list(range(N))

    o_set = ordered_set.OrderedSet(items)
    u_set = set(items)

    to_remove = items[::2]

    for timer in timerit.Timerit(100, bestof=3, label='(Unordered) difference update (inplace)'):
        _u_set = copy.deepcopy(u_set)
        with timer:
            _u_set.difference_update(to_remove)

    for timer in timerit.Timerit(10, bestof=3, label='(Ordered) difference update (inplace)'):
        _o_set = copy.deepcopy(o_set)
        with timer:
            _o_set.difference_update(to_remove)

    for timer in timerit.Timerit(100, bestof=3, label='(Ordered) difference (not inplace)'):
        with timer:
            _new_o_set = o_set.difference(to_remove)

    def _discard_update_alternative(self, *sets):
        import itertools as it
        keys = set(it.chain(*sets))
        _discard_many(self, keys)

    def _discard_many(self, keys):
        """
        sets = [to_remove]
        self = o_set
        """
        idxs = [self.map[key] for key in keys]
        # Remove indices in reverse order
        for idx in sorted(idxs)[::-1]:
            del self.items[idx]

        # Update mapping requires O(N) traversal
        # I don't see any way around it (doesn't mean there isn't one)
        for idx, key in enumerate(self.items):
            self.map[key] = idx

    for timer in timerit.Timerit(100, bestof=3, label='(Ordered) difference update (inplace alt impl)'):
        _o_set_alt = copy.deepcopy(o_set)
        with timer:
            _discard_update_alternative(_o_set_alt, to_remove)

    assert _o_set_alt == _new_o_set
    assert _o_set_alt == _o_set
    assert _u_set == _o_set
```

In these tests I test difference_update with (1) the builtin set class, (2) the OrderedSet class, (3) the non-inplace version of OrderedSet.difference and (4) an alternate implementation of OrderedSet.difference_update. 

The results are clear:

```
Timed best=9.976 µs, mean=10.163 ± 0.1 µs for (Unordered) difference update (inplace)
Timed best=39.947 ms, mean=40.133 ± 0.2 ms for (Ordered) difference update (inplace)
Timed best=367.376 µs, mean=378.990 ± 22.6 µs for (Ordered) difference (not inplace)

Timed best=177.687 µs, mean=187.137 ± 8.0 µs for (Ordered) difference update (inplace alt impl)
```

Unordered set differences are by far the fastest. When N=1000 OrderedSet is 4000x slower than builtins.set.

If one was to use OrderedSet.difference instead of OrderedSet.difference_update, you are only 40x slower, which is much better. 

My alternate implementation of difference_update makes use of a `discard_many` function, which is much more efficient when multiple items are discarded as it saves the O(N) map update until the end. I'm not sure if there is any way around this O(N) update. If there is it would likely require modifying the underlying data structure. However, the O(N) overhead cost is much better than the O(N*M) overhead that was previously incurred. With my alt implementation OrderedSet is only 20x slower than builtins.set. Not perfect, but better. 

The `intersection_update` also has the O(N * M) overhead. It probably makes sense to simply rewrite it in terms of `difference_update`, so we only have to worry about optimizing code in one place. IE: 

```python
    def intersection_update_alt(self, other):
        to_remove = [item for item in self if item not in other]
        self.difference_update(to_remove)
```

**Comment by rspeer** [comment]
Got it.

Note that your `_discard_many` is erroneous: it leaves old values in the map. So they won't be iterated, but they will still look like they're in the OrderedSet.

Reasoning about mutable objects can be tricky, so I'm working on an implementation that just uses one method, called `_update_items`, to replace `.items` and `.map` with new values. It mutates the OrderedSet as seen from the outside, without having to do complex iterate-and-mutate operations on its internals.
