### ISSUE TITLE
Equality comparisons with regular set don't commute

### ISSUE THREAD

**Issue by wimglenn** [LuminosoInsight/ordered-set#55]
Equality with set is not commutative:

```
>>> s = {'x', 'y'}
>>> os = OrderedSet(['x', 'y'])
>>> s == os
False
>>> os == s
True
```

It will be difficult to fix because this returns `False` instead of `NotImplemented`

```
>>> s.__eq__(os)
False
```

I'm not sure the best way forward.  You can allow `OrderedSet.__eq__` to take the precedence if it is a proper set subclass..

**Comment by rspeer** [comment]
Do you think it would be appropriate for OrderedSet to return `False` in this case as well?

**Comment by wimglenn** [comment]
I don't know, that's a tough call because the behaviour in Python changed between 2.7.7 and 2.7.8.  Maybe this package could add the requires_python metadata saying that only 2.7.8+ is supported..

**Comment by rspeer** [comment]
Thanks for finding that out. A little bit of inconsistency with <= 2.7.7 is fine with me, especially as Python 2.7 will only be supported for four more months anyway.

**Comment by rspeer** [comment]
Feel free to take a look at the PR: https://github.com/LuminosoInsight/ordered-set/pull/56

**Comment by wimglenn** [comment]
If you wouldn't mind holding off on merging that, I think the approach proposed in that PR is not a good way forward (and it's a backwards incompatible change, so it certainly shouldn't be made in a minor point release).  I'll prepare an alternate PR which will be offering a more consistent behaviour with how Python's other data structures work.

**Comment by wimglenn** [comment]
See https://github.com/LuminosoInsight/ordered-set/pull/57 for an alternate proposal for how to resolve this issue.
